version: "3"

services:
  postgres-gympoint:
    image: postgres:latest
    ports:
      - "5435:5432"
    volumes:
      - postgres-gympoint:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=gympoint
      - POSTGRES_PASSWORD=postgres

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis:/data

volumes:
  postgres-gympoint:
  redis:
